### ISSUE TITLE
Restore force_parse flag to DatasetManager.run_etl

### ISSUE THREAD

**Issue by ohsqueezy** [Arbol-Project/gridded-etl-tools#70]
More a feature request than a bug. There may be situations where a user might want to force a flow to parse after the extract step even when no new data is detected. A recent example is [this flow](https://app.prefect.cloud/account/bbbe99b4-794e-415f-bca7-cbe6fc435ca7/workspace/0ff4206d-273c-43c1-8b93-9de75fd2e4c6/flow-runs/flow-run/e4bec818-e05f-4929-9622-f17a5563b381) where we were trying to patch an ERA5 dataset that needed to fill a gap caused by a finalization date bug.

I actually think this might be better off implemented in the Prefect repository, and that we should consider removing `DatasetManager.run_etl` in favor of letting implementations decide how to run an ETL, but since Prefect currently uses `run_etl`, I raised the issue in this repo.

**Comment by rbanick** [comment]
Superseded by introduction of `allow_overwrite` and removal of `run_etl`
